# ESPectre - ESP32-C6 Node 4
# WiFi CSI-based motion detection

esphome:
  name: espectre-node4
  friendly_name: "CSI Node 4"
  min_version: 2025.11.0
  project:
    name: francescopace.espectre
    version: "2.2.0"

esp32:
  variant: ESP32C6
  framework:
    type: esp-idf

external_components:
  - source:
      type: git
      url: https://github.com/francescopace/espectre
      ref: main
    components: [ espectre ]
    refresh: 7d

espectre:
  id: espectre_csi

# WiFi - Home network
wifi:
  ssid: "LIMINAL_VEIL"
  password: "whispered_frequency"
  # Fallback AP if connection fails
  ap:
    ssid: "CSI-Node4-Fallback"
    password: "threshold_four"

captive_portal:

# Logging
logger:
  level: INFO

# Home Assistant API (no encryption for easy setup)
api:

# OTA updates
ota:
  - platform: esphome
    password: "ethereal_passage"

# Web server for direct access
web_server:
  port: 80
