# ESPectre - ESP32-C6 Node 3
# WiFi CSI-based motion detection

esphome:
  name: espectre-node3
  friendly_name: "CSI Node 3"
  min_version: 2025.11.0
  project:
    name: francescopace.espectre
    version: "2.2.0"

esp32:
  variant: ESP32C6
  framework:
    type: esp-idf

external_components:
  - source:
      type: git
      url: https://github.com/francescopace/espectre
      ref: main
    components: [ espectre ]
    refresh: always

espectre:
  id: espectre_csi

# WiFi - Hemmanätverk
wifi:
  ssid: "LIMINAL_VEIL"
  password: "whispered_frequency"
  # Fallback AP om den inte kan ansluta
  ap:
    ssid: "CSI-Node3-Fallback"
    password: "threshold_three"

captive_portal:

# Logging
logger:
  level: INFO

# Home Assistant API (utan kryptering för enkel setup)
api:

# OTA updates
ota:
  - platform: esphome
    password: "ethereal_passage"

# Web server för direkt åtkomst
web_server:
  port: 80
